[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kaapos"
version = "0.1.0"
authors = [
  { name="Kaapo Seppänen" },
]
description = "Library for testing thermal integrands"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "symbolica",
]
